In [2]:
import numpy as np

# Задайте размер матрицы
size = 4

# Генерация квадратной матрицы A со случайными элементами
A = np.random.normal(0, 1, (size, size))

# Нахождение собственных значений и собственных векторов
eigenvalues, eigenvectors = np.linalg.eig(A)

# Вывод собственных значений и собственных векторов и матрицы
print("Матрица А:")
print(A)
print("\nСобственные значения:")
print(eigenvalues)
print("\nСобственные векторы:")
print(eigenvectors)

# Нахождение максимального по модулю собственного значения и его индекса
max_eigenvalue_index = np.argmax(np.abs(eigenvalues))
max_eigenvalue = eigenvalues[max_eigenvalue_index]
corresponding_eigenvector = eigenvectors[:, max_eigenvalue_index]

# Вычисление нормы соответствующего собственному значению вектора
norm = np.linalg.norm(corresponding_eigenvector)

# Вывод результата
print("\nМаксимальное по модулю собственное значение:", max_eigenvalue)
print("Соответствующий собственный вектор:")
print(corresponding_eigenvector)
print("Норма соответствующего собственного вектора:", norm)

Матрица А:
[[ 1.12801145  0.16621701 -0.96628563  1.22957147]
 [-1.05139432  0.9385622  -0.0268488  -1.41998236]
 [ 0.09128997 -0.33036369  0.72501415 -0.39088   ]
 [-1.68314418 -0.30277047 -0.72130773 -1.51894017]]

Собственные значения:
[-1.14026233+0.j          0.74073958+0.86676617j  0.74073958-0.86676617j
  0.93143081+0.j        ]

Собственные векторы:
[[ 0.36032117+0.j         -0.71540658+0.j         -0.71540658-0.j
  -0.51375525+0.j        ]
 [-0.37718265+0.j          0.2400665 -0.33033027j  0.2400665 +0.33033027j
  -0.73392959+0.j        ]
 [-0.25505001+0.j          0.20954876+0.33189399j  0.20954876-0.33189399j
   0.24274987+0.j        ]
 [-0.81415686+0.j          0.35755357-0.19883295j  0.35755357+0.19883295j
   0.37212284+0.j        ]]

Максимальное по модулю собственное значение: (-1.140262328917376+0j)
Соответствующий собственный вектор:
[ 0.36032117+0.j -0.37718265+0.j -0.25505001+0.j -0.81415686+0.j]
Норма соответствующего собственного вектора: 1.0
